### ISSUE TITLE
Same Issue 

### ISSUE THREAD

**Issue by Script-Kiddie-JKB** [cheems/BlackPearl-Tutorial-Thread-Generator#4]
![image](https://user-images.githubusercontent.com/78461084/128603366-c112dce2-5b39-4f37-b9cf-e33338dc9533.png)

check once..!!

**Comment by cheems** [comment]
Fixed!
It seems like they are updating the site components these day so element classes are getting changed. Using regex will be a great solution for this but I hate regex patterns because I can't keep remember them in my mind at all. That's why I didn't use it in the code. Anyway if this keep continues will look into do something
